configfile:"config/config.yaml"

IN=config["general"]["samplein"]
OUT=config["general"]["sampleout"]

GENOME=config["genome"]["dir"]+config["genome"]["name"]+config["genome"]["ext"]
EXT=config["raw_spec"]["ext"]
R1=config["raw_spec"]["pairs_ext"][0]
R2=config["raw_spec"]["pairs_ext"][1]


include:"workflow/rules/cooler.smk"
include:"workflow/rules/cutadapt.smk"
include:"workflow/rules/hicstuff.smk"
include:"workflow/rules/juicertools.smk"
include:"workflow/rules/makeChromSize.smk"
include:"workflow/rules/pairtools.smk"

rule all:
	input:
		expand(OUT+"out_{prefix}_{aligner}/{prefix}_hicstuff_{mapping}.{matrix}",
			prefix=config["general"]["samples"],
			aligner=["bowtie2"],
			mapping=["iterative"],
			matrix=["mcool","hic"])
