general:
  samplein: "CH85_S7/RAW/"
  sampleout: "CH85_S7/"
  samples:
    - "CH85_S7"
  threads:
    trimming: 128
    aln: 128
    cooler: 128
    matrix: 128
genome:
  dir: "../NathalieFrederic_HiC/"
  name: "W303"
  ext: ".fa"
raw_spec:
  ext: "_001.gz"
  pairs_expr: "_R[12]"
  pairs_ext: 
    - "_R1"
    - "_R2"
cutadapt:
  adapters: ""
  extra: "--cut 10"
hicstuff:
  aligner:
    - bowtie2
  mapping:
    - iterative
  digestion: "DnpII,HinfI"
  matfmt: "bg2"
  rm_duplicates: true
  supp: "--no-cleanup --centromeres=NathalieFrederic_HiC/centromeres_Sac_ceri_W303.txt --force"
juicer:
  generate_site_positions: "scripts/generate_site_positions.py"
  juicertools: "scripts/juicer_tools_1.22.01.jar"
  resolutions: "500,1000,2000,3000,4000,5000,10000"
  digestion: "Arima"
cooler:
  minres: "500"
  resolutions: "500,1000,2000,3000,4000,5000,10000"
  options: "--balance"
